### ISSUE TITLE
java.security.ProviderException: Failed to generate attestation certificate chain

### ISSUE THREAD

**Issue by mateusz-holysz** [GrapheneOS/Auditor#179]
I have been using GrapheneOS on Pixel 3XL for about 1,5 year. There were no problems with Auditor verification or using attestation service. From January this year (2022), errors started to appear that my device have failed to provide valid attestations before the expiry time. Also when performing audit with second device (without attestation service) there is an error: java.security.ProviderException: Failed to generate attestation certificate chain. 

OS compilation: SP1A.210812.016.C1.2022032110
Auditor version: 44

What data do you need to identify and solve the problem?

Thank You!

**Comment by thestinger** [comment]
This is an OS issue caused by moving to Android 12.1 on the end-of-life Pixel 3 and Pixel 3 XL, not an Auditor issue. This issue didn't start in January but rather with the update to Android 12.1 in March. It's no longer possible to use hardware attestation on the Pixel 3 and Pixel 3 XL due to the issue and we've been unable to resolve it.

**Comment by thestinger** [comment]
It will only be resolved if developers step up to work on improving the legacy support for the end-of-life devices. It definitely made sense to update to the March release despite this breaking.
