### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Perflyst** [GrapheneOS/Auditor#61]
F-Droid is an (you know what it is) installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform.

Would like to see your app there.

**Comment by thestinger** [comment]
It's not my decision about whether it gets published in the official F-Droid repository. It's up to them to choose what they package. Someone else could submit it for inclusion there, but it should be noted that they would need to ship the official signed releases for compatibility with the official releases of the app and https://attestation.app/. Using a different signing key would be incompatible due to how trust is chained from hardware through the OS to the app via the key attestation feature.

I can make sure the builds are reproducible but it's ultimately up to them if they want to include it. If there are issues with reproducible builds that prevent shipping the official releases (which is what would need to be done), I can resolve that.

I'm not particularly interested in making my own F-Droid repository for this because it would only be for people without GrapheneOS. It would be best if it was just in the official repository.

**Comment by rugk** [comment]
It would be great to see this Android app on F-Droid! As such, I strongly suggest to reopen this issue.

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted. As such, if your build is reproducible, yes, the problem with signing keys goes away.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

> It's not my decision about whether it gets published in the official F-Droid repository. It's up to them to choose what they package. 

Yes, but they usually want confirmation from the app author that publishing the app on F-Droid is okay and you support this. It's a matter of kindness, but also 

> If there are issues with reproducible builds that prevent shipping the official releases (which is what would need to be done), I can resolve that.

That's great to hear and of course having a reproducible build is also a good sign for security. :+1: 

> I'm not particularly interested in making my own F-Droid repository for this because it would only be for people without GrapheneOS.

Ehm, what makes you think so?
As far as I see it would be for everyone using F-Droid and having a CustomROM with locked bootloader – or even a StockROM. F-Droid is also quite popular on Stock ROMs when people just disable the Google Play Store, because they cannot yet switch to a CustomROM.
Some other CustomROMs that may want to use this are [CalyxOS](https://calyxos.org/) ([I wrote a summary here](https://forum.fairphone.com/t/privacy-sensitive-os-calyxos-as-an-e-alternative-for-fairphone-3-fp3/66126?u=rugk).), GrapheneOS as you said and AFAIK [/e/ OS](https://e.foundation/).

As such, reopening this would be good. Maybe tag it with "help wanted" as a signal that the community may work on this, but it'S basically just about making the app builds according to the F-Droid requirements (in your case, reproducible) and submitting [a merge request](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests).

/cc @IzzySoft

**Comment by beerisgood** [comment]
@rugk read https://github.com/GrapheneOS/os_issue_tracker/issues/341#issuecomment-699903065

**Comment by thestinger** [comment]
The builds are already reproducible. It does *not* make sense to ship builds of this app signed with a different key, at least without rebranding it and hosting a new copy of the service, since it's not going to be interoperable. The whole point of the app is remote attestation and it verifies the signature and app id of itself on the other end using information in the hardware-based attestation to chain trust through the OS to the app.

If F-Droid wants to ship our builds of the app, that's fine with me. We're not going to be involved in it beyond fixing actual issues with reproducible builds if any ever exist. We're not going to be building in an environment determined by someone else though.

**Comment by thestinger** [comment]
> Some other CustomROMs that may want to use this are CalyxOS (I wrote a summary here.), GrapheneOS as you said and AFAIK /e/ OS.

It does not support operating systems without verified boot and the full security model intact. This app is already included in GrapheneOS and receives updates through it which is why I explained that an F-Droid repository would only really be useful for people with another OS.

**Comment by thestinger** [comment]
Also, again there is nothing that can be done by us downstream. No reason we would have to be the ones to submit it to F-Droid.

**Comment by rugk** [comment]
I already referred to that. CalyxOS and  /e/ OS AFAIK do have verified boot  intact etc. Also even if not, you could use this app to test, whether they have… :wink: 
As for what you can do: Keep reproducible builds working and  

> @rugk read GrapheneOS/os_issue_tracker#341 (comment)

@beerisgood Interesting read, for sure, but as it is also said there, F-Droid seems to have fixed that issue. Anyway, also unrelated to this issue here.

**Comment by thestinger** [comment]
/e/ definitely does not have verified boot and the security model intact. It cannot be supported by Auditor.

**Comment by thestinger** [comment]
The existing builds are already reproducible, as I said above already. There is nothing for us to do. We're definitely not going to change our build environment to match the one used by F-Droid and I see no reason that would be required for reproducible builds. As I said already, there is no reason that we have to be the ones to write the F-Droid metadata and make a request to include this upstream. We're fine with them redistributing the builds of our app after checking that they match a reproduced build. It wouldn't make any sense to distribute a build signed with different keys as I explained above. This is not the right place to request that F-Droid include an app in their repository.

**Comment by rugk** [comment]
Okay, opened a packaging request: https://gitlab.com/fdroid/rfp/-/issues/1550

**Comment by rugk** [comment]
Okay, so some news from that F-Droid thread:
1. The app is even useful for when a phone does not support verified boot etc., because you say on your website:
   > Any device with Android 7.0 or later can run the Auditor app and use it to verify other devices.

   As such, I guess, you can still verify a verified-boot-device from a non-verified-boot-device.
2. What you could do to simplify F-Droid inclusion is [using fastlane structurres](https://gitlab.com/snippets/1895688) for metadata (also compatible with Google Play AFAIK).
3. You do [include some binary files here](https://github.com/GrapheneOS/Auditor/tree/master/app/src/main/res/raw) – where do these come from? Is there any source code for them?

**Comment by thestinger** [comment]
> The app is even useful for when a phone does not support verified boot etc.

Android 7+ devices without support for verified boot, attestation and the rest of the standard security model can be used as auditors. However, they aren't going to be particularly good auditors.

The minimum version will likely be increased to Android 8+ soon because Android 7 is more than 3 years old and no longer receives security updates. A device without full security updates is not going to be a particularly useful auditor device. Increasing the minimum version will allow us to simplify the existing code and more easily implement new improvements.

> What you could do to simplify F-Droid inclusion is using fastlane structurres for metadata (also compatible with Google Play AFAIK).

Maintaining this kind of information in another place isn't something that appeals to us.

> You do include some binary files here – where do these come from? Is there any source code for them?

They're certificates included as assets, not code. I recommend looking at the file names and the commits adding them. Those are the official attestation root certificates and DEFLATE dictionaries based on concatenating the sample certificates. The commits adding the DEFLATE dictionaries added the sample certificates to the repository. If you want to reproduce generating the dictionaries you can run `cat samples/1/*`. It's a static dictionary to improve compression. QR codes can only hold up to 2953 bytes of binary data and very good, reliable compression is required to reliably fit the data into them. The RSA attestation roots are too large to fit without having them in the static dictionary. Ideally, there would be an ECDSA attestation root for ECDSA attestation certificate chains. I'm not sure why they haven't added one yet. We don't want to make users scan multiple QR codes and I'm not aware of a good replacement for QR codes able to transfer more data. It would also be a lot of work to implement.

**Comment by thestinger** [comment]
If you want us to add fastlane metadata you'll need to send a pull request with the basics. Maintaining changelogs in the Git repository itself isn't very appealing to us but we can consider it. You'll need to send an initial PR with the basic metadata and then follow-up pull requests demonstrating what's required. We could add the same screenshots that are used for the Play Store.

Maintaining changelogs within the same Git repository isn't very appealing to us. It means that the changelog has to be finalized before tagging a release and then changes to the changelog are going to be in the history of changes which is messy. It's not really how we want to handle it. Other metadata is much less problematic. The only acceptable way to include changelogs in the repository would be if they're simply links to the release notes like https://github.com/GrapheneOS/Auditor/releases/tag/22. It would be fine to add a link to the release notes with that kind of metadata for each release.

**Comment by thestinger** [comment]
> The app is even useful for when a phone does not support verified boot etc.

I said above that publishing the app via F-Droid would only be useful for users without GrapheneOS and therefore we aren't particularly interested in working on it ourselves. We're fully supportive of people who want to work on that, and you're welcome to work on it. You'll need to do the work though. It seems that you've misinterpreted what I wrote about this above.

Android 7+ devices without support for verified boot, attestation and the rest of the standard security model can be used as auditors. However, they aren't going to be particularly good auditors.

The minimum version will likely be increased to Android 8+ soon because Android 7 is more than 3 years old and no longer receives security updates. A device without full security updates is not going to be a particularly useful auditor device. Increasing the minimum version will allow us to simplify the existing code and more easily implement new improvements.

> What you could do to simplify F-Droid inclusion is using fastlane structurres for metadata (also compatible with Google Play AFAIK).

Maintaining this kind of information in another place isn't something that appeals to us.

> You do include some binary files here – where do these come from? Is there any source code for them?

They're certificates included as assets, not code. I recommend looking at the file names and the commits adding them. Those are the official attestation root certificates and DEFLATE dictionaries based on concatenating the sample certificates. The commits adding the DEFLATE dictionaries added the sample certificates to the repository. If you want to reproduce generating the dictionaries you can run `cat samples/1/*`. It's a static dictionary to improve compression. QR codes can only hold up to 2953 bytes of binary data and very good, reliable compression is required to reliably fit the data into them. The RSA attestation roots are too large to fit without having them in the static dictionary. Ideally, there would be an ECDSA attestation root for ECDSA attestation certificate chains. I'm not sure why they haven't added one yet. We don't want to make users scan multiple QR codes and I'm not aware of a good replacement for QR codes able to transfer more data. It would also be a lot of work to implement.

**Comment by thestinger** [comment]
> The app is even useful for when a phone does not support verified boot etc.

I said above that publishing the app via F-Droid would only be useful for users without GrapheneOS and therefore we aren't particularly interested in working on it ourselves. We're fully supportive of people who want to work on that, and you're welcome to work on it. You'll need to do the work though. It seems that you've misinterpreted what I wrote about this above.

Android 7+ devices without support for verified boot, attestation and the rest of the standard security model can be used as auditors. However, they aren't going to be particularly good auditors.

The minimum version will likely be increased to Android 8+ soon because Android 7 is more than 3 years old and no longer receives security updates. A device without full security updates is not going to be a particularly useful auditor device. Increasing the minimum version will allow us to simplify the existing code and more easily implement new improvements.

> What you could do to simplify F-Droid inclusion is using fastlane structurres for metadata (also compatible with Google Play AFAIK).

If you want us to add fastlane metadata you'll need to send a pull request with the basics and we can maintain it from there. We could add the same screenshots that are used for the Play Store but you'll need to send a follow-up pull request demonstrating a working setup for it. If you want us to add something that has no use for us, we need you to do most of the work.

Maintaining changelogs within the same Git repository isn't very appealing to us. It means that the changelog has to be finalized before tagging a release and then changes to the changelog are going to be in the history of changes which is messy. I don't think we're going to be willing to do this. Look at the mess this creates in our repository for the GrapheneOS website with the GrapheneOS release notes. I don't want to be dealing with that in an important repository like this one where the history should be as clean and easy to follow as possible. The only acceptable way to include changelogs in the repository would be if they're simply links to the release notes like https://github.com/GrapheneOS/Auditor/releases/tag/22. It would be fine to add a link to the release notes with that kind of metadata for each release. If that is acceptable, we can do that. I'll need someone to submit sample metadata for this doing it for the next release (version code and name `23`) and then I can start doing it from that point forwards. I'm happy to maintain the metadata after someone adds it, but I'm not going to do it from scratch. We have no use for it ourselves.

> You do include some binary files here – where do these come from? Is there any source code for them?

They're certificates included as assets, not code. I recommend looking at the file names and the commits adding them. Those are the official attestation root certificates and DEFLATE dictionaries based on concatenating the sample certificates. The commits adding the DEFLATE dictionaries added the sample certificates to the repository. If you want to reproduce generating the dictionaries you can run `cat samples/1/*`. It's a static dictionary to improve compression. QR codes can only hold up to 2953 bytes of binary data and very good, reliable compression is required to reliably fit the data into them. The RSA attestation roots are too large to fit without having them in the static dictionary. Ideally, there would be an ECDSA attestation root for ECDSA attestation certificate chains. I'm not sure why they haven't added one yet. We don't want to make users scan multiple QR codes and I'm not aware of a good replacement for QR codes able to transfer more data. It would also be a lot of work to implement.

**Comment by IzzySoft** [comment]
> The only acceptable way to include changelogs in the repository would be if they're simply links to the release notes like https://github.com/GrapheneOS/Auditor/releases/tag/22. It would be fine to add a link to the release notes with that kind of metadata for each release. If that is acceptable, we can do that.

That would be appreciated. And we just point to `releases/` with the generic `Changelog:` for the (entire) app then – as it's currently done already [in my repo](https://apt.izzysoft.de/fdroid/index/apk/app.attestation.auditor). Well, so that's already done – just keep adding the release notes as you already do :smiley:

> They're certificates included as assets, not code.

That should be fine. @rugk we can put that to `scanignore:` then with some proper `MaintainerNotes:`. But better have a packager approve; I'm "just" the Metadata guy :laughing:

@thestinger more details (for Fastlane) in my PR. Feel free to ping me when needed with that.

**Comment by rugk** [comment]
BTW we're getting nearer to an F-Droid release: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9620

**Comment by thestinger** [comment]
We're now distributing Auditor through our own app repository. Our app repository client is still in an early alpha stage but already has a much nicer metadata signing system with proper whole file signing and key rotation for metadata, unattended app update support without any privileged app permissions and fits properly into Android's model of one app being one app source for the purpose of users / device managers authorizing app sources via the OS. We'll be making sure it has proper support for split APKs, library APKs, updating library APKs in sync with the apps using them when there are strict version dependencies (Chromium), delta updates, compressed transfer of apks while still having proper resume support, etc. It's something we can actually hope to make robust, secure and usable. F-Droid has not addressed many serious usability / security issues and is still targeting API 25 (Android 7.1) and using legacy package installation APIs.

I've become aware that numerous people involved in the F-Droid world are spreading misinformation about GrapheneOS and falsely accusing us of doing that about their project because they have an issue with us making something better suited to our requirements. The mix of technical issues and problems like this is why we chose not to continue bundling F-Droid. F-Droid's strong ties to a certain highly malicious project has increasingly become relevant too.

I don't see much point in further work on this. I'd rather end up having users using our app repository to keep it updated anyway. Perhaps I should just remove the added metadata and ask for it not to be packaged to close the door on it and we can instead focus on building something better. Not just a better design and implementation, but a better community where underhanded and unethical behavior including harassment, plagiarism and libel aren't tolerated.

**Comment by thestinger** [comment]
F-Droid project members are increasingly engaged in underhanded attacks on GrapheneOS. We expect the misinformation to be retracted and for the people involved in these attacks to apologize. If nothing changes this week, F-Droid project members and contributors will be banned from the GrapheneOS community going forward.

**Comment by moparisthebest** [comment]
I don't know who you think you are, but f-droid is a great group of volunteers providing an excellent service for all Android users and it's ridiculous for a project that simply forks Android, and adds nothing meaningful other than a pitiful attempt at "adding security" and more vendor lock-in to make threats like this. You should be ashamed of yourself and apologize.

**Comment by Menelmacar** [comment]
I'm not part of F-droid or graphene or anything.
I'm just an end user.

I wonder where are all these attacks? And how does one know its official from the fdroid team and not just "people on the internet"
Its sad to see this hatred in the community, and I wonder if there is really no professional cooperation possible.

**Comment by thestinger** [comment]
F-Droid project members and contributors are banned from our community going forward due to the coordinated spreading of misinformation, harassment, bullying and other underhanded behavior.

**Comment by thestinger** [comment]
F-Droid project members coordinating spreading misinformation about GrapheneOS, brigading our issue tracker and harassing our developers is unacceptable. F-Droid project members and contributors are banned from participation in our community going forward. Will be banning anyone who contributes to it from our rooms, issue tracker and elsewhere. Posting more abusive attacks on the project is not helping your case.
