### ISSUE TITLE
"Remote verification \\ Failed to submit remote attestation."

### ISSUE THREAD

**Issue by mdempsky** [GrapheneOS/Auditor#62]
My Pixel 3 XL is configured to remote attest to attestation.app every 4 hours. It's been sync'ing okay since Sep 2, but since Nov 1 it fails to attest. The only debugging details I seem to have are the Auditor app has a notification panel entry reporting "Remote verification \\ Failed to submit remote attestation."

**Comment by thestinger** [comment]
Do you have access to another Android device that you could install Auditor on to verify your Pixel 3 XL using the local verification functionality? That would be a good way to get more information.

Alternatively, you could use `adb logcat` to see what's going wrong with it. Auditor will currently locally verify the attestation before submitting it, which is a development aid that will likely be removed in the long term to provide better error reporting from the service. It's likely that it isn't actually trying to contact the server at all, since it's probably rejecting the invalid attestation locally.

One common issue for verification between devices is desynced time, but that wouldn't be a problem for the local verification before sending the attestation.

It might help to fully power off the device and then power it back up (not just a reboot), in case something went wrong with the firmware / hardware state.

Another possibility is that it's just failing to contact the server. Unfortunately, I haven't developed a way to actually report the errors locally for failures yet, so you'll need `adb logcat` from an attached computer to figure out what's actually going wrong if it's an issue like this.

**Comment by mdempsky** [comment]
Thanks for the quick response!

> It might help to fully power off the device and then power it back up (not just a reboot), in case something went wrong with the firmware / hardware state.

This seems to have fixed it. Full power off and then power back on, and now it successfully sync'ed to the attestation server. Thanks for the tip.

Let me know if you want me to try any of the other steps still, otherwise I'm happy to consider this issue resolved. It might be nice if clicking the "Failed to submit remote attestion." alert took you to a wiki page or something with additional debugging steps like you just described.

**Comment by thestinger** [comment]
The issue with a normal reboot is that while it fully wipes the state of the main memory, etc. some components may not actually get their power cut and start up again, so it's not an entirely fresh slate. I'd guess that the problem was something like a hardware-based timer/clock screwing up, or something along those lines. Unfortunately, hardware has weird quirks that happen on rare occasions. I'd guess that you'll never run into the problem again, or at least it will be extremely rare, but maybe one day someone else will hit it. It's hard to know what the problem was though.

> Let me know if you want me to try any of the other steps still, otherwise I'm happy to consider this issue resolved. It might be nice if clicking the "Failed to submit remote attestion." alert took you to a wiki page or something with additional debugging steps like you just described.

Yeah, it would probably be a good idea to add some more stuff to the tutorial on https://attestation.app/ and link to it from error messages.

**Comment by thestinger** [comment]
Titan M firmware is also not super mature yet and probably has some bugs. So far, I've never seen anything not fixed by a full power off and on though, and problems are rare. I'm very interested in https://opensource.googleblog.com/2019/11/opentitan-open-sourcing-transparent.html since it would be great if they moved to this for the Titan M and I could actually review the high level source code directly, report bugs to a proper bug tracker and make proposals via sketched out patches (although I wouldn't be able to easily test them).
