### ISSUE TITLE
wrong attestation app package name: UnknownPackage

### ISSUE THREAD

**Issue by daradib** [GrapheneOS/Auditor#92]
Recent remote attestations failed. Tried creating a new verification pairing as auditee and after the QR code was scanned the app displayed:

    Error encountered generating attestation:
    wrong attestation app package name: UnknownPackage

Error persisted after force stopping and clearing the app cache. Error disappeared after restarting the device, so perhaps a bug in PackageManager (call to [pm.getKeyAttestationApplicationId](https://android.googlesource.com/platform/system/security/+/refs/heads/master/keystore/keystore_attestation_id.cpp)?). The device is a Pixel 3 XL running GrapheneOS RQ2A.210305.006.2021.03.06.00.

**Comment by thestinger** [comment]
It could be an issue communication with the secure element. I think it must be an upstream bug and it's highly unlikely that you're going to run into it again. I don't think we'll be able to figure out what's wrong. I've had issues with the older generation Titan M which required rebooting the device before including with timestamps.

**Comment by thestinger** [comment]
Going to close this because I don't think there's much we can do especially for an older generation device. I don't think it's a PackageManager issue but rather the secure element is not giving the OS the value that it has stored on it for the key for some reason. It's basically not something we could even begin to debug or fix. If the OS was providing the wrong value to it then it wouldn't be resolved by a reboot and wouldn't be allowing usage of the key either.

**Comment by thestinger** [comment]
Also, by clearing the app cache, do you mean clearing data for the app completely?

**Comment by daradib** [comment]
Thanks for clarifying - that explanation makes more sense. I'll post back if it unexpectedly fails again.

> Also, by clearing the app cache, do you mean clearing data for the app completely?

Kept the app data, just clicked the clear cache button in app info after force stopping. The attestation pairing fingerprint remained the same.
